name: Update Google Calendar
on: push

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: bundle install
      - run: |
          echo "$GCAL_CREDENTIALS" > credentials.json
          echo "$GCAL_TOKEN" > token.yml
        env:
          GCAL_CREDENTIALS: ${{ secrets.GCAL_CREDENTIALS }}
          GCAL_TOKEN: ${{ secrets.GCAL_TOKEN }}
      - run: bundle exec scma-gcal -o gcal
        env:
          SCMA_USERNAME: ${{ secrets.SCMA_USERNAME }}
          SCMA_PASSWORD: ${{ secrets.SCMA_PASSWORD }}
