name: Update Google Calendar
on: push

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: bundle install
      - run: bundle exec scma-gcal
        env:
          SCMA_USERNAME: ${{ secrets.SCMA_USERNAME }}
          SCMA_PASSWORD: ${{ secrets.SCMA_PASSWORD }}
